// DE/EN synonym mapping
export const SYNONYMS: Record<string, string[]> = {
  "bau": ["construction", "building", "build", "baustelle"],
  "construction": ["bau", "building"],
  "baustelle": ["site", "construction site"],
  "site": ["baustelle", "construction site"],
  "erdbau": ["earthworks", "excavation", "aushub"],
  "earthworks": ["erdbau", "excavation"],
  "aushub": ["excavation", "dig", "digging"],
  "excavation": ["aushub", "dig"],
  "fundament": ["foundation", "basis"],
  "foundation": ["fundament", "base"],
  "beton": ["concrete"],
  "concrete": ["beton"],
  "rohbau": ["shell", "structure"],
  "shell": ["rohbau", "structure"],
  "abdichtung": ["waterproofing", "sealing"],
  "waterproofing": ["abdichtung", "sealing"],
  "dach": ["roof", "roofing"],
  "roof": ["dach", "roofing"],
  "fassade": ["facade", "exterior"],
  "facade": ["fassade", "exterior"],
  "außen": ["exterior", "outside", "external"],
  "exterior": ["außen", "outside"],
  "innen": ["interior", "inside", "internal"],
  "interior": ["innen", "inside"],
  "fenster": ["window", "windows"],
  "window": ["fenster"],
  "tür": ["door", "doors"],
  "door": ["tür"],
  "sanitär": ["plumbing", "sanitary"],
  "plumbing": ["sanitär", "pipes"],
  "heizung": ["heating", "radiator"],
  "heating": ["heizung", "heat"],
  "elektro": ["electrical", "electric"],
  "electrical": ["elektro", "power"],
  "strom": ["power", "electricity"],
  "power": ["strom", "electricity"],
  "trockenbau": ["drywall", "partition"],
  "drywall": ["trockenbau", "gypsum"],
  "maler": ["painting", "paint"],
  "painting": ["maler", "paint"],
  "boden": ["floor", "flooring"],
  "floor": ["boden", "flooring"],
  "fliesen": ["tiles", "tiling"],
  "tiles": ["fliesen", "tiling"],
  "parkett": ["parquet", "wood floor"],
  "außenanlage": ["external works", "landscaping"],
  "landscaping": ["außenanlage", "garden"],
  "zugang": ["access", "entry"],
  "access": ["zugang", "entry"],
  "schwer": ["difficult", "hard"],
  "difficult": ["schwer", "hard"],
  "erschwert": ["difficult", "challenging"],
  "entsorgung": ["disposal", "waste"],
  "disposal": ["entsorgung", "waste"],
  "schutt": ["debris", "rubble"],
  "debris": ["schutt", "waste"],
  "bohrung": ["drilling", "bore"],
  "drilling": ["bohrung", "bore"],
  "montage": ["installation", "install", "assembly"],
  "installation": ["montage", "install"],
  "verlegen": ["lay", "install", "laying"],
  "lay": ["verlegen", "install"]
};